variables:
  CIBW_TEST_COMMAND: "pip install -r {project}/requirements/tests.txt && pytest --pyargs uarray"
  CIBW_BUILD: cp38-* pp3?-*
  CIBW_BEFORE_BUILD: "git status"
  CIBW_BEFORE_TEST: "git status"

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - template: ci/azure-steps.yml
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: ci/azure-steps.yml


trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'

pr:
- master
